# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ceb968e368eb62a88b5ea3b7bcf1281d2869da0fab4820fa5b52feb4129521a0f5ab7b2e2fd25bc0a658687580b8c24a08466ea6736af2f565071a8e1beacab1

test:
  secret_key_base: 69e121b90cf70d4fdad3354a7faeb91bfcebb03219fa46b69f39b49861aef0af11e879377963894f19425244a97c43afdb83d7f098768037f69fc85a4291ec94

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
